<!DOCTYPE HTML>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Error Handling - </title>
        <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <base href="">

        <link rel="stylesheet" href="book.css">
        <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

        <link rel="shortcut icon" href="favicon.png">

        <!-- Font Awesome -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

        <link rel="stylesheet" href="highlight.css">
        <link rel="stylesheet" href="tomorrow-night.css">

        <!-- MathJax -->
        <script type="text/javascript" src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>

        <!-- Fetch JQuery from CDN but have a local fallback -->
        <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
        <script>
            if (typeof jQuery == 'undefined') {
                document.write(unescape("%3Cscript src='jquery.js'%3E%3C/script%3E"));
            }
        </script>
    </head>
    <body class="light">
        <!-- Set the theme before any content is loaded, prevents flash -->
        <script type="text/javascript">
            var theme = localStorage.getItem('theme');
            if (theme == null) { theme = 'light'; }
            $('body').removeClass().addClass(theme);
        </script>

        <!-- Hide / unhide sidebar before it is displayed -->
        <script type="text/javascript">
            var sidebar = localStorage.getItem('sidebar');
            if (sidebar === "hidden") { $("html").addClass("sidebar-hidden") }
            else if (sidebar === "visible") { $("html").addClass("sidebar-visible") }
        </script>

        <div id="sidebar" class="sidebar">
            <ul class="chapter"><li class="affix"><a href="./readme.html">Introduction</a></li><li><a href="./1-basics.html"><strong>1.</strong> Basics</a></li><li><a href="./2-structs-enums-lifetimes.html"><strong>2.</strong> Structs, Enums and Matching</a></li><li><a href="./3-filesystem.html"><strong>3.</strong> Filesystem and Processes</a></li><li><a href="./4-modules.html"><strong>4.</strong> Modules and Cargo</a></li><li><a href="./5-stdlib-containers.html"><strong>5.</strong> Standard Library Containers</a></li><li><a href="./6-error-handling.html" class="active"><strong>6.</strong> Error Handling</a></li><li><a href="./7-shared-and-networking.html"><strong>7.</strong> Threads, Networking and Sharing</a></li></ul>
        </div>

        <div id="page-wrapper" class="page-wrapper">

            <div class="page">
                <div id="menu-bar" class="menu-bar">
                    <div class="left-buttons">
                        <i id="sidebar-toggle" class="fa fa-bars"></i>
                        <i id="theme-toggle" class="fa fa-paint-brush"></i>
                    </div>

                    <h1 class="menu-title"></h1>

                    <div class="right-buttons">
                        <i id="print-button" class="fa fa-print" title="Print this book"></i>
                    </div>
                </div>

                <div id="content" class="content">
                    <a class="header" href="./6-error-handling.html#error-handling" name="error-handling"><h1>Error Handling</h1></a>
<a class="header" href="./6-error-handling.html#basic-error-handling" name="basic-error-handling"><h2>Basic Error Handling</h2></a>
<p>Error handling in Rust can be clumsy if you can't use the question-mark operator.
To achieve happiness, we need to create our own error type. The basic requirements
are straightforward:</p>
<ul>
<li>May implement <code>Debug</code></li>
<li>Must implement <code>Display</code></li>
<li>Must implement <code>Error</code></li>
</ul>
<p>Otherwise, your error can do pretty much what it likes.</p>
<pre><pre class="playpen"><code class="language-rust"># #![allow(unused_variables)]
# 
#fn main() {
// error1.rs
use std::error::Error;
use std::fmt;

#[derive(Debug)]
struct MyError {
    details: String
}

impl MyError {
    fn new(msg: &amp;str) -&gt; MyError {
        MyError{details: msg.to_string()}
    }
}

impl fmt::Display for MyError {
    fn fmt(&amp;self, f: &amp;mut fmt::Formatter) -&gt; fmt::Result {
        write!(f,&quot;{}&quot;,self.details)
    }
}


impl Error for MyError {
    fn description(&amp;self) -&gt; &amp;str {
        &amp;self.details
    }
}

// a test function that returns our error result
fn raises_my_error(yes: bool) -&gt; Result&lt;(),MyError&gt; {
    if yes {
        Err(MyError::new(&quot;borked&quot;))
    } else {
        Ok(())
    }
}

#}</code></pre></pre>
<p>In this example we need to handle the specific error when a string can't be parsed
as a floating-point number. It implements <code>Error</code> so <code>description()</code> is defined.</p>
<p>Now the way that <code>?</code> works
is to look for a conversion from the error of the expression to the error that must
be returned. And this conversion is expressed by the <code>From</code> trait:</p>
<pre><pre class="playpen"><code class="language-rust"># #![allow(unused_variables)]
# 
#fn main() {
impl From&lt;std::num::ParseFloatError&gt; for MyError {
    fn from(err: std::num::ParseFloatError) -&gt; Self {
        MyError::new(err.description())
    }
}

// and test!
fn parse_f64(s: &amp;str, yes: bool) -&gt; Result&lt;f64,MyError&gt; {
    raises_my_error(yes)?;
    let x: f64 = s.parse()?;
    Ok(x)
}

#}</code></pre></pre>
<p>The first <code>?</code> is fine (a type always converts to itself with <code>From</code>) and the
second <code>?</code> needs to convert from <code>ParseFloatError</code> to <code>MyError</code>.</p>
<p>And the results:</p>
<pre><pre class="playpen"><code class="language-rust">fn main() {
    println!(&quot; {:?}&quot;, parse_f64(&quot;42&quot;,false));
    println!(&quot; {:?}&quot;, parse_f64(&quot;42&quot;,true));
    println!(&quot; {:?}&quot;, parse_f64(&quot;?42&quot;,false));
}
//  Ok(42)
//  Err(MyError { details: &quot;borked&quot; })
//  Err(MyError { details: &quot;invalid float literal&quot; })
</code></pre></pre>
<p>Not too complicated, although a little long-winded. The tedious bit is having to
write <code>From</code> conversions for all the other error types that need to play nice
with <code>MyError</code>.  But once the mechanism is in place, your error handling looks
much cleaner!</p>
<p>Typing <code>Result&lt;T,MyError&gt;</code> gets tedious and many Rust modules define their own
<code>Result</code> - e.g. <code>io::Result&lt;T&gt;</code> is short for <code>io::Result&lt;T,io::Error&gt;</code>.</p>
<p>Currently, the question-mark operator only works for <code>Result</code>, not <code>Option</code>, and this can be seen
as a feature, not a limitation.  <code>Option</code> has a <code>ok_or_else</code> which converts itself into a <code>Result</code>.
For example, say we had a <code>HashMap</code> and must fail if a key isn't defined:</p>
<pre><pre class="playpen"><code class="language-rust"># #![allow(unused_variables)]
# 
#fn main() {
    let val = map.get(&quot;my_key&quot;).ok_or_else(|| MyError::new(&quot;my_key not defined&quot;))?;

#}</code></pre></pre>
<p>Now here the error returned is completely clear! (This form uses a closure, so the error value
is only created if the lookup fails.)</p>
<a class="header" href="./6-error-handling.html#error-chain-to-the-rescue" name="error-chain-to-the-rescue"><h2>error-chain to the Rescue</h2></a>
<p>Error handling is important, and for non-trivial applications have a look
at the <a href="http://brson.github.io/2016/11/30/starting-with-error-chain">error_chain</a> crate.
A little macro magic can go a long way in Rust...</p>
<p>Create a binary crate with <code>cargo new --bin test-error-chain</code> and
change to this directory. Edit <code>Cargo.toml</code> and add <code>error-chain=&quot;0.8.1&quot;</code> to the end.</p>
<p>What <strong>error-chain</strong> does for you is create all the definitions we needed for manually implementing
an error type; creating a struct, and implementing the necessary traits: <code>Display</code>, <code>Debug</code> and <code>Error</code>.
It also by default implements <code>From</code> so strings can be converted into errors. Here we also ask for
<code>From</code> to be implemented so that <code>std::io::Error</code> will also convert into our error type.</p>
<p>Our first <code>src/main.rs</code> file looks like this. All the main program does is call <code>run</code>, print out any
errors, and end the program with a non-zero exit code.  The macro <code>error_chain</code> generates all the
definitions needed, within an <code>error</code> module - in a larger program you would put this in its own file.
We need to bring everything in <code>error</code> back into global scope because our code will need to see
the generated traits. By default, there will be an <code>Error</code> struct and a <code>Result</code> defined with that
error:</p>
<pre><pre class="playpen"><code class="language-rust">#[macro_use]
extern crate error_chain;

mod errors {
    error_chain!{
        foreign_links {
            Io(::std::io::Error);
        }
    }
}
use errors::*;

fn run() -&gt; Result&lt;()&gt; {
    use std::fs::File;

    File::open(&quot;file&quot;)?;

    Ok(())
}


fn main() {
    if let Err(e) = run() {
        println!(&quot;error: {}&quot;, e);

        std::process::exit(1);
    }
}
// error: No such file or directory (os error 2)
</code></pre></pre>
<p>The 'foreign_links' has made our life easier, since the question mark operator now knows how to
convert <code>std::io::Error</code> into our <code>error::Error</code>.</p>
<p>All the action happens in <code>run</code>; let's make it print out the first 10 lines of a file given as the
first program argument.  There may or may not be such an argument, which isn't necessarily an
error. Here we want to convert an <code>Option&lt;String&gt;</code> into a <code>Result&lt;String&gt;</code>. There are two <code>Option</code>
methods for doing this conversion, and I've picked the simplest one.  Our <code>Error</code> type implements
<code>From</code> for <code>&amp;str</code>, so it's straightforward to make an error with a simple text message.</p>
<pre><pre class="playpen"><code class="language-rust"># #![allow(unused_variables)]
# 
#fn main() {
fn run() -&gt; Result&lt;()&gt; {
    use std::env::args;
    use std::fs::File;
    use std::io::BufReader;
    use std::io::prelude::*;

    let file = args().skip(1).next()
        .ok_or(Error::from(&quot;provide a file&quot;))?;

    let f = File::open(&amp;file)?;
    let mut l = 0;
    for line in BufReader::new(f).lines() {
        let line = line?;
        println!(&quot;{}&quot;, line);
        l += 1;
        if l == 10 {
            break;
        }
    }

    Ok(())
}

#}</code></pre></pre>
<p>There is a useful little macro <code>bail!</code> for 'throwing' errors.
An alternative to the <code>ok_or</code> method here could be:</p>
<pre><pre class="playpen"><code class="language-rust"># #![allow(unused_variables)]
# 
#fn main() {
    let file = match args().skip(1).next() {
        Some(s) =&gt; s,
        None =&gt; bail!(&quot;provide a file&quot;)
    };

#}</code></pre></pre>
<p>Like <code>?</code> it does an <em>early return</em>.</p>
<p>The returned error contains an enum <code>ErrorKind</code>, which allows us to distinguish between various
kinds of errors. There's always a variant <code>Msg</code> (when you say <code>Error::from(str)</code>) and the <code>foreign_links</code>
macro has declared <code>Io</code> which wraps I/O errors:</p>
<pre><pre class="playpen"><code class="language-rust">fn main() {
    if let Err(e) = run() {
        match e.kind() {
            &amp;ErrorKind::Msg(ref s) =&gt; println!(&quot;msg {}&quot;,s),
            &amp;ErrorKind::Io(ref s) =&gt; println!(&quot;io {}&quot;,s),
        }
        std::process::exit(1);
    }
}
// $ cargo run
// msg provide a file
// $ cargo run foo
// io No such file or directory (os error 2)
</code></pre></pre>
<p>It's straightforward to add new kinds of errors. Add an <code>errors</code> section to the <code>error_chain!</code> macro:</p>
<pre><pre class="playpen"><code class="language-rust"># #![allow(unused_variables)]
# 
#fn main() {
    error_chain!{
        foreign_links {
            Io(::std::io::Error);
        }

        errors {
            NoArgument(t: String) {
                display(&quot;no argument provided: '{}'&quot;, t)
            }
        }

    }

#}</code></pre></pre>
<p>This defines how <code>Display</code> works for this new kind of error. And now we can handle
'no argument' errors more specifically, feeding <code>ErrorKind::NoArgument</code> a <code>String</code> value:</p>
<pre><pre class="playpen"><code class="language-rust"># #![allow(unused_variables)]
# 
#fn main() {
    let file = args().skip(1).next()
        .ok_or(ErrorKind::NoArgument(&quot;filename needed&quot;.to_string()))?;


#}</code></pre></pre>
<p>There's now an extra <code>ErrorKind</code> variant that you must match:</p>
<pre><pre class="playpen"><code class="language-rust">fn main() {
    if let Err(e) = run() {
        println!(&quot;error {}&quot;,e);
        match e.kind() {
            &amp;ErrorKind::Msg(ref s) =&gt; println!(&quot;msg {}&quot;, s),
            &amp;ErrorKind::Io(ref s) =&gt; println!(&quot;io {}&quot;, s),
            &amp;ErrorKind::NoArgument(ref s) =&gt; println!(&quot;no argument {:?}&quot;, s),
        }
        std::process::exit(1);
    }
}
// cargo run
// error no argument provided: 'filename needed'
// no argument &quot;filename needed&quot;
</code></pre></pre>
<p>Generally, it's useful to make errors as specific as possible, <em>particularly</em> if this is a library
function! This match-on-kind technique is pretty much the equivalent of traditional exception handling,
where you match on exception types.</p>
<p>In summary, <strong>error-chain</strong> creates a type <code>Error</code> for you, and defines <code>Result&lt;T&gt;</code> to be <code>std::result::Result&lt;T,Error&gt;</code>.
<code>Error</code> contains an enum <code>ErrorKind</code> and by default there is one variant <code>Msg</code> for errors created from
strings. You define 'foreign' errors with <code>foreign_links</code> which does two things. First, it creates a new
<code>ErrorKind</code> variant. Second, it defines <code>From</code> on these external errors so they can be converted to our
error.  New error variants can be easily added.  A lot of irritating boilerplate code is eliminated.</p>
<a class="header" href="./6-error-handling.html#chaining-errors" name="chaining-errors"><h2>Chaining Errors</h2></a>
<p>But the really cool thing that this crate provides is <em>error chaining</em>.</p>
<p>As a <em>library user</em>, it's irritating when a method simply just 'throws' a generic I/O error. OK, it
could not open a file, fine, but what file? Basically, what use is this information to me?</p>
<p><code>error_chain</code> does <em>error chaining</em> which helps solve this problem of over-generic errors. When we
try to open the file, we can lazily lean on the conversion to <code>io::Error</code> using <code>?</code> or chain the error.</p>
<pre><pre class="playpen"><code class="language-rust"># #![allow(unused_variables)]
# 
#fn main() {
// non-specific error
let f = File::open(&amp;file)?;

// a specific chained error
let f = File::open(&amp;file).chain_err(|| &quot;unable to read the damn file&quot;)?;

#}</code></pre></pre>
<p>Here's a new version of the program, with <em>no</em> imported 'foreign' errors, just the defaults:</p>
<pre><pre class="playpen"><code class="language-rust">#[macro_use]
extern crate error_chain;

mod errors {
    error_chain!{
    }

}
use errors::*;

fn run() -&gt; Result&lt;()&gt; {
    use std::env::args;
    use std::fs::File;
    use std::io::BufReader;
    use std::io::prelude::*;

    let file = args().skip(1).next()
        .ok_or(Error::from(&quot;filename needed&quot;))?;

    ///////// chain explicitly! ///////////
    let f = File::open(&amp;file).chain_err(|| &quot;unable to read the damn file&quot;)?;

    let mut l = 0;
    for line in BufReader::new(f).lines() {
        let line = line.chain_err(|| &quot;cannot read a line&quot;)?;
        println!(&quot;{}&quot;, line);
        l += 1;
        if l == 10 {
            break;
        }
    }

    Ok(())
}


fn main() {
    if let Err(e) = run() {
        println!(&quot;error {}&quot;, e);

        /////// look at the chain of errors... ///////
        for e in e.iter().skip(1) {
            println!(&quot;caused by: {}&quot;, e);
        }

        std::process::exit(1);
    }
}
// $ cargo run foo
// error unable to read the damn file
// caused by: No such file or directory (os error 2)
</code></pre></pre>
<p>So the <code>chain_err</code> method takes the original error, and creates a new error which contains the
original error - this can be continued indefinitely.  The closure is expected to return any
value which can be <em>converted</em> into an error.</p>
<p>Rust macros can clearly save you a lot of typing.  <code>error-chain</code> even provides a shortcut that
replaces the whole main program:</p>
<pre><pre class="playpen"><code class="language-rust"># #![allow(unused_variables)]
# 
#fn main() {
quick_main!(run);

#}</code></pre></pre>
<p>(<code>run</code> is where all the action takes place, anyway.)</p>

                </div>

                <!-- Mobile navigation buttons -->
                
                    <a href="./5-stdlib-containers.html" class="mobile-nav-chapters previous">
                        <i class="fa fa-angle-left"></i>
                    </a>
                

                
                    <a href="./7-shared-and-networking.html" class="mobile-nav-chapters next">
                        <i class="fa fa-angle-right"></i>
                    </a>
                

            </div>

            
                <a href="./5-stdlib-containers.html" class="nav-chapters previous" title="You can navigate through the chapters using the arrow keys">
                    <i class="fa fa-angle-left"></i>
                </a>
            

            
                <a href="./7-shared-and-networking.html" class="nav-chapters next" title="You can navigate through the chapters using the arrow keys">
                    <i class="fa fa-angle-right"></i>
                </a>
            

        </div>


        <!-- Local fallback for Font Awesome -->
        <script>
            if ($(".fa").css("font-family") !== "FontAwesome") {
                $('<link rel="stylesheet" type="text/css" href="_FontAwesome/css/font-awesome.css">').prependTo('head');
            }
        </script>

        <!-- Livereload script (if served using the cli tool) -->
        

        <script src="highlight.js"></script>
        <script src="book.js"></script>
    </body>
</html>
